name: fspo310
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.8.3=py310h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=hf384b4a_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.15.1.6=h2e68323_0
  - libcurand=10.4.0.35=h50d9014_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.3.0=py310hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.14.0=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - urllib3=2.5.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - click==8.2.2
      - cloudpickle==3.1.1
      - codetiming==1.4.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.1.0
      - decorator==5.2.1
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.116.2
      - flash-attn==2.6.3
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - hydra-core==1.3.2
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - ipdb==0.13.13
      - ipython==8.37.0
      - jedi==0.19.2
      - jiter==0.11.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - liger-kernel==0.6.2
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.6
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - minicheck==0.1.0
      - mistral-common==1.8.5
      - modelscope==1.31.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - omegaconf==2.3.0
      - openai==1.108.0
      - opencv-python-headless==4.11.0.86
      - orjson==3.11.3
      - outlines==0.0.46
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post6
      - peft==0.17.1
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - prometheus-client==0.23.0
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==21.0.0
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pygments==2.19.2
      - pylatexenc==2.10
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyzmq==27.1.0
      - ray==2.49.2
      - referencing==0.36.2
      - regex==2025.9.1
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.38.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.48.0
      - tensordict==0.5.0
      - tiktoken==0.11.0
      - tokenizers==0.22.0
      - tomli==2.2.1
      - torch==2.4.0+cu124
      - torchaudio==2.4.0+cu124
      - torchdata==0.11.0
      - torchvision==0.19.0+cu124
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.56.1
      - triton==3.0.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.6.3
      - wandb==0.21.4
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - xformers==0.0.27.post2
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /mnt/shared-storage-user/liyafu/runquan/miniconda3/envs/fspo310
